import type { Metadata } from "next";
import { IBM_Plex_Mono, Poppins, DM_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mohd Sahil Siddiqui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className} ${ibmPlexMono.className} antialiased`}
      >
        <div className="w-full border-b border-gray-800">
          <div className="py-5 px-4 w-full md:w-2/4 mx-auto text-center">
            <Navbar />
          </div>
        </div>

        <div className="py-5 px-4 w-full md:w-2/4 mx-auto">{children}</div>
      </body>
    </html>
  );
}
